name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - '**/tasky/**'
      - '.github/workflows/docker-build-and-push.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: 047719620374.dkr.ecr.us-west-2.amazonaws.com
      IMAGE_NAME: tasky
      IMAGE_TAG: v20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG ./tasky

      - name: Push Docker image
        run: |
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

